# Site
repository: Jasonlee1995/Jasonlee1995.github.io
favicon: images/avatar.png

# Content configuration version
version: 2

# Personal info
name: Jae Seong Lee
title: Computer Vision Researcher
email: jacklee95@naver.com
# email_title: Email (Email title override)
phone:
# phone_title: Phone (Phone title override)
website:
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username:
github_username:  Jasonlee1995
stackoverflow_username:
dribbble_username:
facebook_username:
flickr_username:
instagram_username:
linkedin_username:
xing_username:
pinterest_username:
youtube_username:
googleplus_username:
orcid_username:

# Additional icon links
#additional_links:
#- title:
  #icon:
  #url:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/avatar.png
about_content: | # this will include new lines to allow paragraphs
  Highly motivated on learning new things related with deep learning.
  Currently interested on narrowing the gap between academic and industry fields.

  Currently, I'm working as
  - machine learning engineer in [<mark>DeepBio</mark>](https://www.deepbio.co.kr/)
  - research intern in [<mark>DAVIAN Lab</mark>](http://davian.uldesign17.co.kr/)
  - computer vision & deep learning seminar, study team leader in [<mark>PoolC</mark>](https://poolc.org/)
  - computer vision seminar, study team leader in [<mark>DIYA</mark>](https://blog.diyaml.com/)

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: YONSEI University
        sub_title: BA on Mechanical Engineering
        caption: 2014.03 - 2021.02
        link: https://www.yonsei.ac.kr/sc/
  - title: Language
    layout: list
    content:
      - layout: left
        title: Korean
        sub_title: Mother Tongue
      - layout: left
        title: English
        sub_title: Fluent
        description: |
          - TOEIC 840 (LC 435, RC 405) on 2022.02.20.
          - OPIc IM2 on 2020.04.08.
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: DeepBio
        sub_title: Machine Learning Engineer
        caption: 2021.09 - present
        link: https://www.deepbio.co.kr/
        description: |
          - Research Field 1. Learning General Representation on Pathology Images
          - Research Field 2. Self-supervised Learning on Pathology Images
      - layout: left
        title: TmaxAI
        sub_title: Computer Vision Researcher
        caption: 2020.12 - 2021.08
        link: https://www.tmax.co.kr/tmaxai
        description: |
          - Research Field 1. OCR with Low-quality Labels
          - Research Field 2. Augmentation for Detection & Classification
          - Research Field 3. Table Recognition and Data Preprocessing
      - layout: left
        title: SOTALabs
        sub_title: Computer Vision Researcher
        caption: 2020.09 - 2020.11
        link: https://www.rocketpunch.com/companies/sotalabs
        description: |
          - Research Field 1. Fashion Image Retrieval
          - Research Field 2. Fashion Image Multi-label Tagging
      - layout: left
        title: NAVER Corporation
        sub_title: AI RUSH Intern
        caption: 2020.08 - 2020.08
        link: https://www.naver.com/
        description: |
          - Research Field 1. Learning General Representation on Noisy Image Dataset
          - Research Field 2. Music Genre Classification with Meta Information
      - layout: left
        title: (주)누아
        sub_title: Research Intern
        caption: 2019.12 - 2020.01
        link: https://www.rocketpunch.com/companies/ju-nua/jobs
        description: |
          - Research Field 1. Rotated Image Generation
          - Research Field 2. Subword Tokenizer for Korean
  - title: Lab Experience
    layout: list
    content:
      - layout: left
        title: DAVIAN Lab
        sub_title: Research Intern
        caption: 2022.03 - present
        link: http://davian.uldesign17.co.kr/
        description: |
          - Research Field 1. Research on Learning De-biased Representation from Biased Dataset
          - Research Field 2. Research on Out-of-Distribution Detection
      - layout: left
        title: Visual Intelligence Lab
        sub_title: Research Intern
        caption: 2021.06 - 2021.11
        link: https://sites.google.com/yonsei.ac.kr/vi-lab/
        description: |
          - Research Field 1. Research on GAN Detection
          - Research Field 2. Research on Self-supervised Learning
      - layout: left
        title: Computer Vision Lab
        sub_title: Undergraduate Research Intern
        caption: 2020.07 - 2020.08
        link: https://cvlab.yonsei.ac.kr/
        description: |
          - Research Field 1. Research on Person Re-Identification
          - Research Field 2. Research on Pedestrian Attribute Recognition
      - layout: left
        title: SEVERANCE Hospital
        sub_title: Undergraduate Intern
        caption: 2020.04 - 2020.06
        link: https://sev.severance.healthcare/sev/index.do
        description: |
          - Worked under [Professor Ahn](https://www.medieus.com/sub_detail/doctor_detail.asp?doc_num=46346)
          - [Paper](https://pubmed.ncbi.nlm.nih.gov/32827069/) Published on Neuroradiology
          - Research Field 1. X-ray Image Joint Detection
          - Research Field 2. Brain Tumor Image Segmentation and Classification
      - layout: left
        title: Knowledge Based Design Lab
        sub_title: Undergraduate Intern
        caption: 2019.01 - 2020.06
        link: https://kbd.yonsei.ac.kr/
        description: |
          - Research Field 1. SEPSIS Prediction
          - Research Field 2. Autonomous Driving for Mobile Robot
  - title: Competitions
    layout: list
    content:
      - layout: left
        title: 2020 NIPA AI Competition
        link: https://ai-korea.kr/main/main.do
        #link_text: Link Text
        additional_links:
          - title: Source Codes
            icon: fab fa-github
            url: https://github.com/Jasonlee1995/2020_NIPA
        description: |
          - 1st place on Final Competition, KB insurance task
          - 1st place on Preliminary Competition
          - Check competition information, tasks and source codes from github
      - layout: left
        title: 2020 NAVER AI RUSH
        link: https://campaign.naver.com/airush/
        #link_text: Link Text
        description: |
          - NAVER Smartstore spam image filtering
          - Top-rank and join as intern
      - layout: left
        title: 2019 Summer NDM Contest
        link: https://cafe.naver.com/nexonndm
        #link_text: Link Text
        additional_links:
          - title: Project Link
            #icon: fab fa-github
            url: https://poolc.org/project/12
        description: |
          - 1st place as university
          - Top-view mobile 2D shooting game with Unity
      - layout: left
        title: 2018 Summer LINE Game Development Club Contest
        link: https://linepluscorp.com/
        #link_text: Link Text
        additional_links:
          - title: Project Link
            #icon: fab fa-github
            url: https://poolc.org/project/10
        description: |
          - 2nd place as team
          - Mobile 2D shooting game with Unity
  - title: Other Activities
    layout: list
    content:
      - layout: left
        title: PoolC
        sub_title: Computer Vision & Deep Learning Seminar and Study Team Lead
        caption: 2017.03 - present
        link: https://poolc.org/
      - layout: left
        title: DIYA
        sub_title: Computer Vision Project and Study Team Lead
        caption: 2018.03 - present
        link: https://blog.diyaml.com/
      - layout: left
        title: elice
        sub_title: Data Coach
        caption: 2022.04 - 2022.05
        link: https://elice.io/
      - layout: left
        title: LIKELION
        sub_title: AI Assistant Instructor
        caption: 2020.10 - 2020.12
        link: https://www.likelion.net/
      - layout: left
        title: HYUNDAI AutoEver
        sub_title: Smart Mobility HW & SW Mentor
        caption: 2018.08 - 2018.10
        link: http://hyundaiautoeversmart.com/
      - layout: left
        title: Mandatory Military Service
        sub_title: ROKAF 10th Fighter Wing, MP
        caption: 2015.01 - 2017.01


  #- title: A Little More About Me
    #layout: text
    #content: | # this will include new lines to allow paragraphs
    #  This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

    #  Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
