# Site
repository: Jasonlee1995/Jasonlee1995.github.io
favicon: images/avatar.png

# Content configuration version
version: 2

# Personal info
name: Jae Seong Lee
title: Computer Vision Researcher
email: jacklee95@naver.com
# email_title: Email (Email title override)
phone:
# phone_title: Phone (Phone title override)
website:
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username:
github_username:  Jasonlee1995
stackoverflow_username:
dribbble_username:
facebook_username:
flickr_username:
instagram_username:
linkedin_username:
xing_username:
pinterest_username:
youtube_username:
googleplus_username:
orcid_username:

# Additional icon links
#additional_links:
#- title:
  #icon:
  #url:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/avatar.png
about_content: | # this will include new lines to allow paragraphs
  Highly motivated on learning new things related with computer vision.
  Always welcome for discussions and suggestions.

  Currently I'm working as
  - computer vision researcher on [<mark>TmaxAI</mark>](https://www.tmax.co.kr/tmaxai)
  - research intern on [<mark>VI Lab</mark>](https://sites.google.com/yonsei.ac.kr/vi-lab/)
  - computer vision seminar, study team leader on [<mark>PoolC</mark>](https://poolc.org/intro)
  - computer vision seminar, study team leader on [<mark>DIYA</mark>](https://blog.diyaml.com/)

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: YONSEI University
        sub_title: BA on Mechanical Engineering
        caption: 2014.03 - 2021.02
        link: https://www.yonsei.ac.kr/sc/
        #description: | # this will include new lines to allow paragraphs
        #  Description of qualification
  - title: Careers
    layout: list
    content:
      - layout: left
        title: TmaxAI
        sub_title: Computer Vision Researcher
        caption: 2020.12 - present
        link: https://www.tmax.co.kr/tmaxai
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          - Research Field 1. AutoAugment for detection
          - Research Field 2. Table Recognition using detection
        title: LIKELION
        sub_title: AI Assistant Instructor
        caption: 2020.12 - present
        link: https://www.likelion.net/
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          - AI Assistant Instructor for newbies

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project


  #- title: A Little More About Me
    #layout: text
    #content: | # this will include new lines to allow paragraphs
    #  This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

    #  Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
